config/routes.rb
Rails.application.routes.draw do

    resources :users, only: [:create, :new, :update, :show]
    resource :session, only: [:create, :new, :destroy]


    namespace :api, defaults: { format: :json } do
      resources :dogs, only: [:create, :index, :update, :show, :destroy] do
        resources :bookings, only: [:index]
      end
      resources :sitters, only: [:create, :index, :update, :show, :destroy] do
        resources :bookings, only: [:index]
      end

      resources :bookings, only: [:create, :destroy, :update]

      resources :sitter_comments, only: [:create, :index, :show, :destroy]

      resources :comments, only: [:index, :create, :show, :update, :destroy]

    end

    root to: 'static_pages#root'

    get "session/guest", to: 'sessions#guest', as: 'guest'

end

app/models/user.rb
require 'bcrypt'

class User < ActiveRecord::Base
  attr_reader :password

  validates :name, :email, :password_digest, :session_token, presence: true
  validates :email, uniqueness: true
  validates :password, length: {minimum: 4, allow_nil: true}

  has_many :dogs

  has_one :sitter_account, class_name: :Sitter, foreign_key: :user_id

  has_many :comments

  before_validation :ensure_session_token

  def self.find_by_credentials(email, password)
    user = User.find_by_email(email)
    unless user
      message = "Username/Password invalid"
      Rails.logger.info(message)
      raise message
    end
    unless user.is_password?(password)
      message = "Password invalid"
      Rails.logger.info(message)
      raise message
    end
    return user
  end

  def is_password?(password)
    b_crypto = BCrypt::Password.new(self.password_digest)
    b_crypto.is_password?(password)
  end

  def password=(password)
    return unless password

    @password = password
    self.password_digest = BCrypt::Password.create(password)
  end

  def reset_session_token!
    self.session_token = User.generate_session_token
    self.save!
    self.session_token
  end

  private

  def self.generate_session_token
     SecureRandom.urlsafe_base64
  end

  def ensure_session_token
    self.session_token ||= SecureRandom.urlsafe_base64
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      sign_in(@user)
      render json: @user, status: 200
    else
      render json: { error: "Registration failed: #{@user.errors.full_messages.join(', ')}",
                     status: 400
                   },
            status: 400
    end
  end

  def update
    @user = User.find_by_session_token(current_user.session_token)
    if @user.update_attributes(user_params)
      @user.save!
      return
    end
    flash[:errors] =  @user.errors.full_messages
  end

  def show
      @user = User.find(params[:id])
      if @user
          render formats: [:json]
          return
      end
      flash[:errors] = @user.errors.full_messages
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :street_address, :city, :state, :zipcode)
  end
end

app/views/users/new.html.erb
<div class="sign-in-form-container">
  <label>Sign Up!</label>
  <form action="/users" method="post" id="sign-up-form">

    <%= form_auth_token %>

    <div class="form-group">
      <label for="nameInfo">Your Name:</label>
      <input
        type="text"
        name="user[name]"
        class="form-control"
        id="nameInfo"
        placeholder="Enter Name">
    </div>

    <div class="form-group">
      <label for="emailCredential">Email Address:</label>
      <input
        type="email"
        name="user[email]"
        class="form-control"
        id="emailCredential"
        placeholder="Enter Email Address">
    </div>

    <div class="form-group">
      <label for="passwordCredential">Password:</label>
      <input
        type="password"
        name="user[password]"
        class="form-control"
        id="passwordCredential"
        placeholder="Password">
    </div>
    <span><input type="submit"
                 value="Sign Up!"
                 class="btn btn-success">
    <span id="button-spacer">&nbsp</span><%= link_to "Sign In", new_session_url, class: 'btn btn-primary' %></span>
  </form>
</div>