config/routes.rb
Rails.application.routes.draw do

    resources :users, only: [:create, :new, :update, :show]
    resource :session, only: [:create, :new, :destroy]


    namespace :api, defaults: { format: :json } do
      resources :dogs, only: [:create, :index, :update, :show, :destroy] do
        resources :bookings, only: [:index]
      end
      resources :sitters, only: [:create, :index, :update, :show, :destroy] do
        resources :bookings, only: [:index]
      end

      resources :bookings, only: [:create, :destroy, :update]

      resources :sitter_comments, only: [:create, :index, :show, :destroy]

      resources :comments, only: [:index, :create, :show, :update, :destroy]

    end

    root to: 'static_pages#root'

    get "session/guest", to: 'sessions#guest', as: 'guest'

end

app/views/layouts/_footer.html.erb
<!-- Footer -->
<footer>
    <div class="row">
        <div class="col-lg-12">
            <p>Copyright &copy; Canine Care 2017</p>
        </div>
    </div>
</footer>

<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-53662509-1', 'auto');
  ga('send', 'pageview');

</script>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default navbar-fixed-top" role="navigation">
    <div class="container">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="/">
                Canine Care
            </a>
        </div>
        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav navbar-right">
                <li>
                    <a href="#/about">About</a>
                </li>
                <li>
                    <a href="#/services">Services</a>
                </li>
                <li>
                    <a href="#/contact">Contact</a>
                </li>
                <% if signed_in? %>
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">Profile<b class="caret"></b></a>
                        <ul class="dropdown-menu">

                            <% if current_user.sitter_account %>
                              <li>
                                  <a href="#/sitters/<%= current_user.sitter_account.id %>">Go to Sitter Profile</a>
                              </li>
                              <li>
                                  <a href="#/sitters/<%= current_user.sitter_account.id %>/bookings">Bookings</a>
                              </li>
                            <% else %>
                                <li>
                                    <a href="#/sitters/new">Become a Sitter!</a>
                                </li>
                            <% end %>
                            <li>
                                <a href="#/dogs">Your Dogs</a>
                            </li>
                            <li>
                                <a href="#/dogs/new">Add A Dog</a>
                            </li>
                            <li><%= link_to "Sign out", session_url, method: :delete%></li>
                        </ul>
                    </li>
                <% else %>
                    <li>
                        <a href="#/sign_in">Sign In</a>
                    </li>

                    <li>
                        <%= link_to "Enter As Guest", guest_url  %>
                    </li>
                <% end %>
            </ul>
        </div>
        <!-- /.navbar-collapse -->
    </div>
    <!-- /.container -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>

  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="Canine Care Application">
  <meta name="author" content="Peter Bardon">
  <meta name="keyword" content="dogsitting">
  <!-- <link rel="shortcut icon" href="assets/ico/favicon.png"> -->

  <title>Canine Care</title>
  <%= stylesheet_link_tag 'application' %>

  <%= csrf_meta_tags %>
</head>

<body id="canineCareApp" class="flex-row align-items-center">
    <%= render partial: "layouts/header" %>
    <%= yield %>
    <%= render partial: "layouts/footer" %>
</body>
<script> type="text/javascript"
   src="https://maps.googleapis.com/maps/api/js?key=<%= ENV['MAPS_API_KEY']%>"
</script>

<%= javascript_include_tag 'application' %>

<script language="javascript" type="text/javascript" charset="utf-8">
    (function () {
        $(document).ready(function(){
            //Bootstrap the sitters colllection
            // CanineCareApp.Collections.sitters =
            //     new CanineCareApp.Collections.Sitters();
            //Bootstrap the sitters colllection
            // CanineCareApp.Collections.sitters.reset(
            //     "<%= load_sitters %>".replace(/&quot;/g, '"'));
            CanineCareApp.initialize('<%= form_auth_token %>',
                '<%= ENV['MAPS_API_KEY']%>',
                '<%= current_user ? current_user.id : nil %>',
                '<%= session[:session_token] %>');
            CanineCareApp.setFormAuthToken = '<%= form_auth_token %>';

        });
    })();
</script>

</html>

app/views/layouts/sandstone.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "dog_sitting_app" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "sandstone", :media => "all" %>

    <%= yield(:page_stylesheet) if content_for?(:page_stylesheet) %>

  </head>
  <body>


    <%= yield %>


    <!-- Javascripts
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <%= javascript_include_tag "sandstone" %>
    <%= yield(:page_javascript) if content_for?(:page_javascript) %>
  </body>
</html>